//
//  JCKit.h
//  JCKitDemo
//
//  Created by molin.JC on 2016/12/11.
//  Copyright © 2016年 molin. All rights reserved.
//

#import "JCKitMacro.h"

#import "NSBundle+JCBundle.h"
#import "NSURL+JCURL.h"
#import "NSFileManager+JCFileManager.h"
#import "NSArray+JCBlock.h"
#import "NSData+JCData.h"
#import "NSData+JCGZIP.h"
#import "NSDate+JCDate.h"
#import "NSDictionary+JCBlock.h"
#import "NSException+JCException.h"
#import "NSNumber+JCNumber.h"
#import "NSObject+JCObject.h"
#import "NSString+JCString.h"
#import "NSTimer+JCBlock.h"

#import "UINavigationController+JCNavigationAttributes.h"
#import "UIBarButtonItem+JCBlock.h"
#import "UIScrollView+JCScrollView.h"
#import "UIGestureRecognizer+JCBlock.h"
#import "UITableViewCell+JCSeparator.h"
#import "UIApplication+JCApplication.h"
#import "UIButton+JCImageTitleStyle.h"
#import "UIButton+JCButtonSimplify.h"
#import "UIColor+JCColor.h"
#import "UIColor+JCSeries.h"
#import "UIControl+JCControl.h"
#import "UIDevice+JCDevice.h"
#import "UIFont+JCScale.h"
#import "JCFontName.h"
#import "UIImage+JCImage.h"
#import "UIScreen+JCScale.h"
#import "UITextField+JCTextField.h"
#import "CALayer+JCLayer.h"
#import "JCGraphicsUtilities.h"
#import "UIView+JCView.h"
#import "UIWebView+JCJavaScript.h"
#import "UIWebView+JCHTML.h"

#import "JCFPSLabel.h"
#import "JCAdvertisementView.h"
#import "JCPopupBaseView.h"
#import "JCMarqueeControl.h"
#import "JCTextView.h"
#import "JCTableViewCell.h"
#import "JCUIKitFactory.h"

#import "JCSignal.h"
#import "JCSystemManager.h"
#import "JCArchiveTool.h"
#import "JCEncodeModel.h"
#import "JCCache.h"
#import "JCKeyboardManager.h"
#import "NSObject+JCBind.h"
#import "NSObject+JCObserverKVO.h"
#import "UIView+JCLayout.h"
#import "UIView+JCRect.h"
#import "NSObject+JCJSON.h"
#import "JCSQLite3.h"
#import "JCStream.h"
#import "NSObject+JCStram.h"
#import "JCWeakProxy.h"
